/** Generated by scripts/generate-og-images.mjs — do not edit by hand */
export const ogManifest = {
  "routes": {
    "/get-started": {
      "title": "Get Started · PythonTeacher",
      "description": "Setup, study paths, and how to get the most from PythonTeacher.",
      "ogImageId": "get-started"
    },
    "/python-basics": {
      "title": "Python Basics · PythonTeacher",
      "description": "Python from zero: types, control flow, functions, modules, venv, files, and exceptions.",
      "ogImageId": "python-basics"
    },
    "/challenges": {
      "title": "Python Challenges · PythonTeacher",
      "description": "Hands-on Python coding challenges from easy to very hard with acceptance criteria.",
      "ogImageId": "challenges"
    },
    "/flashcards": {
      "title": "Flashcards · PythonTeacher",
      "description": "Quick-review flashcards for FastAPI, pytest, asyncio, RAG, MCP, and more.",
      "ogImageId": "flashcards"
    },
    "/python-patterns": {
      "title": "Python Patterns · PythonTeacher",
      "description": "Python idioms and design patterns with examples for interviews and production code.",
      "ogImageId": "python-patterns"
    },
    "/system-design": {
      "title": "System Design · PythonTeacher",
      "description": "Backend system design problems and interview walkthroughs with Python.",
      "ogImageId": "system-design"
    },
    "/flashcards/agents": {
      "title": "AI Agents · Flashcards",
      "description": "Study 15 flashcards on AI Agents for Python interviews.",
      "ogImageId": "flashcards/agents"
    },
    "/flashcards/async": {
      "title": "Async Python · Flashcards",
      "description": "Study 15 flashcards on Async Python for Python interviews.",
      "ogImageId": "flashcards/async"
    },
    "/flashcards/clean-code": {
      "title": "Clean Code & Patterns · Flashcards",
      "description": "Study 15 flashcards on Clean Code & Patterns for Python interviews.",
      "ogImageId": "flashcards/clean-code"
    },
    "/flashcards/cloud": {
      "title": "Cloud & Python · Flashcards",
      "description": "Study 15 flashcards on Cloud & Python for Python interviews.",
      "ogImageId": "flashcards/cloud"
    },
    "/flashcards/data-eng": {
      "title": "Data Engineering · Flashcards",
      "description": "Study 15 flashcards on Data Engineering for Python interviews.",
      "ogImageId": "flashcards/data-eng"
    },
    "/flashcards/data-structures": {
      "title": "Data Structures · Flashcards",
      "description": "Study 15 flashcards on Data Structures for Python interviews.",
      "ogImageId": "flashcards/data-structures"
    },
    "/flashcards/databases": {
      "title": "Databases · Flashcards",
      "description": "Study 15 flashcards on Databases for Python interviews.",
      "ogImageId": "flashcards/databases"
    },
    "/flashcards/devops": {
      "title": "DevOps for Python · Flashcards",
      "description": "Study 15 flashcards on DevOps for Python for Python interviews.",
      "ogImageId": "flashcards/devops"
    },
    "/flashcards/fastapi": {
      "title": "FastAPI · Flashcards",
      "description": "Study 15 flashcards on FastAPI for Python interviews.",
      "ogImageId": "flashcards/fastapi"
    },
    "/flashcards/flask": {
      "title": "Flask · Flashcards",
      "description": "Study 15 flashcards on Flask for Python interviews.",
      "ogImageId": "flashcards/flask"
    },
    "/flashcards/functions": {
      "title": "Functions · Flashcards",
      "description": "Study 15 flashcards on Functions for Python interviews.",
      "ogImageId": "flashcards/functions"
    },
    "/flashcards/llm-apps": {
      "title": "LLM Applications · Flashcards",
      "description": "Study 15 flashcards on LLM Applications for Python interviews.",
      "ogImageId": "flashcards/llm-apps"
    },
    "/flashcards/mcp": {
      "title": "Model Context Protocol · Flashcards",
      "description": "Study 15 flashcards on Model Context Protocol for Python interviews.",
      "ogImageId": "flashcards/mcp"
    },
    "/flashcards/oop": {
      "title": "Object-Oriented Python · Flashcards",
      "description": "Study 15 flashcards on Object-Oriented Python for Python interviews.",
      "ogImageId": "flashcards/oop"
    },
    "/flashcards/performance": {
      "title": "Performance · Flashcards",
      "description": "Study 15 flashcards on Performance for Python interviews.",
      "ogImageId": "flashcards/performance"
    },
    "/flashcards/pytest": {
      "title": "pytest · Flashcards",
      "description": "Study 15 flashcards on pytest for Python interviews.",
      "ogImageId": "flashcards/pytest"
    },
    "/flashcards/fundamentals": {
      "title": "Python Fundamentals · Flashcards",
      "description": "Study 15 flashcards on Python Fundamentals for Python interviews.",
      "ogImageId": "flashcards/fundamentals"
    },
    "/flashcards/rag": {
      "title": "RAG · Flashcards",
      "description": "Study 15 flashcards on RAG for Python interviews.",
      "ogImageId": "flashcards/rag"
    },
    "/flashcards/stdlib": {
      "title": "Standard Library · Flashcards",
      "description": "Study 15 flashcards on Standard Library for Python interviews.",
      "ogImageId": "flashcards/stdlib"
    },
    "/flashcards/typing": {
      "title": "Type Hints & Typing · Flashcards",
      "description": "Study 15 flashcards on Type Hints & Typing for Python interviews.",
      "ogImageId": "flashcards/typing"
    },
    "/challenges/easy": {
      "title": "Easy Challenges · PythonTeacher",
      "description": "20 easy Python coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/easy"
    },
    "/challenges/easy/01-fizzbuzz": {
      "title": "FizzBuzz · Easy",
      "description": "Easy Python challenge: FizzBuzz. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/01-fizzbuzz"
    },
    "/challenges/easy/02-string-parsing": {
      "title": "Log Line Parser · Easy",
      "description": "Easy Python challenge: Log Line Parser. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/02-string-parsing"
    },
    "/challenges/easy/03-file-counter": {
      "title": "File Line Counter · Easy",
      "description": "Easy Python challenge: File Line Counter. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/03-file-counter"
    },
    "/challenges/easy/04-json-reader": {
      "title": "JSON Config Reader · Easy",
      "description": "Easy Python challenge: JSON Config Reader. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/04-json-reader"
    },
    "/challenges/easy/05-cli-args": {
      "title": "CLI Greeting · Easy",
      "description": "Easy Python challenge: CLI Greeting. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/05-cli-args"
    },
    "/challenges/easy/06-simple-class": {
      "title": "Bank Account Class · Easy",
      "description": "Easy Python challenge: Bank Account Class. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/06-simple-class"
    },
    "/challenges/easy/07-list-dict-operations": {
      "title": "Inventory Totals · Easy",
      "description": "Easy Python challenge: Inventory Totals. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/07-list-dict-operations"
    },
    "/challenges/easy/08-pathlib-walk": {
      "title": "Find Python Files · Easy",
      "description": "Easy Python challenge: Find Python Files. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/08-pathlib-walk"
    },
    "/challenges/easy/09-env-vars": {
      "title": "Environment Config · Easy",
      "description": "Easy Python challenge: Environment Config. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/09-env-vars"
    },
    "/challenges/easy/10-pytest-basics": {
      "title": "Pytest Temperature · Easy",
      "description": "Easy Python challenge: Pytest Temperature. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/10-pytest-basics"
    },
    "/challenges/easy/11-csv-parse": {
      "title": "CSV Sales Report · Easy",
      "description": "Easy Python challenge: CSV Sales Report. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/11-csv-parse"
    },
    "/challenges/easy/12-requests-get": {
      "title": "HTTP GET JSON · Easy",
      "description": "Easy Python challenge: HTTP GET JSON. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/12-requests-get"
    },
    "/challenges/easy/13-dataclass": {
      "title": "User Profile Dataclass · Easy",
      "description": "Easy Python challenge: User Profile Dataclass. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/13-dataclass"
    },
    "/challenges/easy/14-enum": {
      "title": "Order Status Enum · Easy",
      "description": "Easy Python challenge: Order Status Enum. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/14-enum"
    },
    "/challenges/easy/15-logging": {
      "title": "Module Logger Setup · Easy",
      "description": "Easy Python challenge: Module Logger Setup. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/15-logging"
    },
    "/challenges/easy/16-config-file": {
      "title": "TOML App Config · Easy",
      "description": "Easy Python challenge: TOML App Config. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/16-config-file"
    },
    "/challenges/easy/17-unit-converter": {
      "title": "Unit Converter · Easy",
      "description": "Easy Python challenge: Unit Converter. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/17-unit-converter"
    },
    "/challenges/easy/18-password-validator": {
      "title": "Password Validator · Easy",
      "description": "Easy Python challenge: Password Validator. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/18-password-validator"
    },
    "/challenges/easy/19-text-search": {
      "title": "Grep Lite · Easy",
      "description": "Easy Python challenge: Grep Lite. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/19-text-search"
    },
    "/challenges/easy/20-api-client": {
      "title": "REST API Client · Easy",
      "description": "Easy Python challenge: REST API Client. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/20-api-client"
    },
    "/challenges/medium": {
      "title": "Medium Challenges · PythonTeacher",
      "description": "28 medium Python coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/medium"
    },
    "/challenges/medium/01-decorator-timing": {
      "title": "Timing Decorator · Medium",
      "description": "Medium Python challenge: Timing Decorator. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/01-decorator-timing"
    },
    "/challenges/medium/02-context-manager": {
      "title": "Timer Context Manager · Medium",
      "description": "Medium Python challenge: Timer Context Manager. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/02-context-manager"
    },
    "/challenges/medium/03-generator-pipeline": {
      "title": "Generator Pipeline · Medium",
      "description": "Medium Python challenge: Generator Pipeline. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/03-generator-pipeline"
    },
    "/challenges/medium/04-dataclass-validation": {
      "title": "Validated Dataclass · Medium",
      "description": "Medium Python challenge: Validated Dataclass. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/04-dataclass-validation"
    },
    "/challenges/medium/05-pytest-fixtures-mocks": {
      "title": "Pytest Fixtures and Mocks · Medium",
      "description": "Medium Python challenge: Pytest Fixtures and Mocks. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/05-pytest-fixtures-mocks"
    },
    "/challenges/medium/06-flask-blueprint": {
      "title": "Flask Blueprint · Medium",
      "description": "Medium Python challenge: Flask Blueprint. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/06-flask-blueprint"
    },
    "/challenges/medium/07-fastapi-crud": {
      "title": "FastAPI CRUD · Medium",
      "description": "Medium Python challenge: FastAPI CRUD. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/07-fastapi-crud"
    },
    "/challenges/medium/08-pydantic-models": {
      "title": "Pydantic Models · Medium",
      "description": "Medium Python challenge: Pydantic Models. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/08-pydantic-models"
    },
    "/challenges/medium/09-sqlalchemy-models": {
      "title": "SQLAlchemy Models · Medium",
      "description": "Medium Python challenge: SQLAlchemy Models. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/09-sqlalchemy-models"
    },
    "/challenges/medium/10-async-gather": {
      "title": "Async Gather · Medium",
      "description": "Medium Python challenge: Async Gather. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/10-async-gather"
    },
    "/challenges/medium/11-aiohttp-client": {
      "title": "Aiohttp Client Wrapper · Medium",
      "description": "Medium Python challenge: Aiohttp Client Wrapper. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/11-aiohttp-client"
    },
    "/challenges/medium/12-retry-decorator": {
      "title": "Retry Decorator · Medium",
      "description": "Medium Python challenge: Retry Decorator. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/12-retry-decorator"
    },
    "/challenges/medium/13-caching-decorator": {
      "title": "Caching Decorator · Medium",
      "description": "Medium Python challenge: Caching Decorator. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/13-caching-decorator"
    },
    "/challenges/medium/14-typer-cli": {
      "title": "Typer CLI · Medium",
      "description": "Medium Python challenge: Typer CLI. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/14-typer-cli"
    },
    "/challenges/medium/15-structured-logging": {
      "title": "Structured Logging · Medium",
      "description": "Medium Python challenge: Structured Logging. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/15-structured-logging"
    },
    "/challenges/medium/16-pydantic-settings": {
      "title": "Pydantic Settings · Medium",
      "description": "Medium Python challenge: Pydantic Settings. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/16-pydantic-settings"
    },
    "/challenges/medium/17-repository-pattern": {
      "title": "Repository Pattern · Medium",
      "description": "Medium Python challenge: Repository Pattern. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/17-repository-pattern"
    },
    "/challenges/medium/18-service-layer": {
      "title": "Service Layer · Medium",
      "description": "Medium Python challenge: Service Layer. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/18-service-layer"
    },
    "/challenges/medium/19-webhook-handler": {
      "title": "Webhook Handler · Medium",
      "description": "Medium Python challenge: Webhook Handler. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/19-webhook-handler"
    },
    "/challenges/medium/20-pagination": {
      "title": "API Pagination · Medium",
      "description": "Medium Python challenge: API Pagination. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/20-pagination"
    },
    "/challenges/medium/21-file-upload": {
      "title": "File Upload · Medium",
      "description": "Medium Python challenge: File Upload. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/21-file-upload"
    },
    "/challenges/medium/22-background-task": {
      "title": "Background Tasks · Medium",
      "description": "Medium Python challenge: Background Tasks. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/22-background-task"
    },
    "/challenges/medium/23-email-sender": {
      "title": "Email Sender · Medium",
      "description": "Medium Python challenge: Email Sender. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/23-email-sender"
    },
    "/challenges/medium/24-rate-limiter": {
      "title": "Rate Limiter · Medium",
      "description": "Medium Python challenge: Rate Limiter. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/24-rate-limiter"
    },
    "/challenges/medium/25-schema-validation": {
      "title": "JSON Schema Validation · Medium",
      "description": "Medium Python challenge: JSON Schema Validation. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/25-schema-validation"
    },
    "/challenges/medium/26-test-coverage": {
      "title": "Test Coverage Setup · Medium",
      "description": "Medium Python challenge: Test Coverage Setup. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/26-test-coverage"
    },
    "/challenges/medium/27-docker-compose": {
      "title": "Docker Compose Stack · Medium",
      "description": "Medium Python challenge: Docker Compose Stack. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/27-docker-compose"
    },
    "/challenges/medium/28-dependency-injection": {
      "title": "Dependency Injection · Medium",
      "description": "Medium Python challenge: Dependency Injection. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/28-dependency-injection"
    },
    "/challenges/hard": {
      "title": "Hard Challenges · PythonTeacher",
      "description": "8 hard Python coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/hard"
    },
    "/challenges/hard/01-fastapi-auth": {
      "title": "FastAPI JWT Auth · Hard",
      "description": "Hard Python challenge: FastAPI JWT Auth. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/01-fastapi-auth"
    },
    "/challenges/hard/02-async-db-pool": {
      "title": "Async DB Pool · Hard",
      "description": "Hard Python challenge: Async DB Pool. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/02-async-db-pool"
    },
    "/challenges/hard/03-celery-tasks": {
      "title": "Celery Tasks · Hard",
      "description": "Hard Python challenge: Celery Tasks. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/03-celery-tasks"
    },
    "/challenges/hard/04-rag-ingestion": {
      "title": "RAG Document Ingestion · Hard",
      "description": "Hard Python challenge: RAG Document Ingestion. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/04-rag-ingestion"
    },
    "/challenges/hard/05-openai-structured-output": {
      "title": "OpenAI Structured Output · Hard",
      "description": "Hard Python challenge: OpenAI Structured Output. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/05-openai-structured-output"
    },
    "/challenges/hard/06-multi-agent-orchestrator": {
      "title": "Multi-Agent Orchestrator · Hard",
      "description": "Hard Python challenge: Multi-Agent Orchestrator. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/06-multi-agent-orchestrator"
    },
    "/challenges/hard/07-performance-profiling": {
      "title": "Performance Profiling · Hard",
      "description": "Hard Python challenge: Performance Profiling. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/07-performance-profiling"
    },
    "/challenges/hard/08-production-dockerfile": {
      "title": "Production Dockerfile · Hard",
      "description": "Hard Python challenge: Production Dockerfile. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/08-production-dockerfile"
    },
    "/challenges/very-hard": {
      "title": "Very Hard Challenges · PythonTeacher",
      "description": "5 very hard Python coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/very-hard"
    },
    "/challenges/very-hard/01-mcp-server": {
      "title": "MCP Server · Very Hard",
      "description": "Very Hard Python challenge: MCP Server. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/01-mcp-server"
    },
    "/challenges/very-hard/02-production-rag": {
      "title": "Production RAG Pipeline · Very Hard",
      "description": "Very Hard Python challenge: Production RAG Pipeline. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/02-production-rag"
    },
    "/challenges/very-hard/03-event-sourced-domain": {
      "title": "Event-Sourced Domain · Very Hard",
      "description": "Very Hard Python challenge: Event-Sourced Domain. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/03-event-sourced-domain"
    },
    "/challenges/very-hard/04-distributed-task-scheduler": {
      "title": "Distributed Task Scheduler · Very Hard",
      "description": "Very Hard Python challenge: Distributed Task Scheduler. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/04-distributed-task-scheduler"
    },
    "/challenges/very-hard/05-llm-agent-memory": {
      "title": "LLM Agent Memory · Very Hard",
      "description": "Very Hard Python challenge: LLM Agent Memory. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/05-llm-agent-memory"
    },
    "/system-design/rate-limited-api": {
      "title": "Rate-Limited API · System Design",
      "description": "Backend system design: FastAPI middleware, Redis counters. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/rate-limited-api"
    },
    "/system-design/url-shortener": {
      "title": "URL Shortener · System Design",
      "description": "Backend system design: Base62 codes, cache-aside. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/url-shortener"
    },
    "/system-design/task-queue": {
      "title": "Task Queue · System Design",
      "description": "Backend system design: Celery/RQ workers, retries. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/task-queue"
    },
    "/system-design/realtime-chat": {
      "title": "Real-Time Chat · System Design",
      "description": "Backend system design: WebSockets, Redis pub/sub. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/realtime-chat"
    },
    "/system-design/auth-system": {
      "title": "Auth System · System Design",
      "description": "Backend system design: JWT + refresh tokens. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/auth-system"
    },
    "/system-design/file-upload-s3": {
      "title": "File Upload (S3) · System Design",
      "description": "Backend system design: Presigned URLs, multipart. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/file-upload-s3"
    },
    "/system-design/search-autocomplete": {
      "title": "Search Autocomplete · System Design",
      "description": "Backend system design: Debounced API, caching. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/search-autocomplete"
    },
    "/system-design/analytics-pipeline": {
      "title": "Analytics Pipeline · System Design",
      "description": "Backend system design: Event ingestion, aggregation. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/analytics-pipeline"
    },
    "/system-design/multi-tenant-saas": {
      "title": "Multi-Tenant SaaS · System Design",
      "description": "Backend system design: Org scoping, row-level security. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/multi-tenant-saas"
    },
    "/system-design/notification-service": {
      "title": "Notification Service · System Design",
      "description": "Backend system design: Push, email, in-app inbox. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/notification-service"
    },
    "/system-design/payment-webhooks": {
      "title": "Payment Webhooks · System Design",
      "description": "Backend system design: Idempotency, signature verify. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/payment-webhooks"
    },
    "/system-design/caching-redis": {
      "title": "Caching (Redis) · System Design",
      "description": "Backend system design: Cache-aside, TTL, invalidation. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/caching-redis"
    },
    "/system-design/scheduled-jobs": {
      "title": "Scheduled Jobs · System Design",
      "description": "Backend system design: Cron, APScheduler, Celery beat. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/scheduled-jobs"
    },
    "/system-design/log-aggregation": {
      "title": "Log Aggregation · System Design",
      "description": "Backend system design: Structured logs, correlation IDs. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/log-aggregation"
    },
    "/system-design/feature-flags": {
      "title": "Feature Flags · System Design",
      "description": "Backend system design: Rollouts, A/B bucketing. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/feature-flags"
    },
    "/system-design/rag-qa-api": {
      "title": "RAG Q&A API · System Design",
      "description": "Backend system design: Embeddings, chunking, retrieval. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/rag-qa-api"
    },
    "/system-design/llm-agent-tools": {
      "title": "LLM Agent with Tools · System Design",
      "description": "Backend system design: Tool use, orchestration. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/llm-agent-tools"
    },
    "/system-design/vector-search": {
      "title": "Vector Search · System Design",
      "description": "Backend system design: pgvector, similarity search. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/vector-search"
    },
    "/system-design/etl-pipeline": {
      "title": "ETL Pipeline · System Design",
      "description": "Backend system design: Batch ingest, transforms. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/etl-pipeline"
    },
    "/system-design/observability-stack": {
      "title": "Observability Stack · System Design",
      "description": "Backend system design: Metrics, traces, alerts. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/observability-stack"
    },
    "/system-design/multi-region-deploy": {
      "title": "Multi-Region Deploy · System Design",
      "description": "Backend system design: Active-passive, failover. Interview walkthrough on PythonTeacher.",
      "ogImageId": "system-design/multi-region-deploy"
    },
    "/python-patterns/comprehensions": {
      "title": "Comprehensions · Python Patterns",
      "description": "Python pattern guide: List, dict, set builders. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/comprehensions"
    },
    "/python-patterns/context-managers": {
      "title": "Context Managers · Python Patterns",
      "description": "Python pattern guide: with and resource cleanup. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/context-managers"
    },
    "/python-patterns/decorators": {
      "title": "Decorators · Python Patterns",
      "description": "Python pattern guide: Wrap functions cleanly. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/decorators"
    },
    "/python-patterns/generators": {
      "title": "Generators · Python Patterns",
      "description": "Python pattern guide: Lazy sequences. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/generators"
    },
    "/python-patterns/dataclasses": {
      "title": "Dataclasses · Python Patterns",
      "description": "Python pattern guide: Structured data objects. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/dataclasses"
    },
    "/python-patterns/protocols": {
      "title": "Protocols · Python Patterns",
      "description": "Python pattern guide: Structural typing. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/protocols"
    },
    "/python-patterns/dependency-injection": {
      "title": "Dependency Injection · Python Patterns",
      "description": "Python pattern guide: Testable services. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/dependency-injection"
    },
    "/python-patterns/repository-pattern": {
      "title": "Repository Pattern · Python Patterns",
      "description": "Python pattern guide: Data access abstraction. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/repository-pattern"
    },
    "/python-patterns/factory-pattern": {
      "title": "Factory Pattern · Python Patterns",
      "description": "Python pattern guide: Object creation. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/factory-pattern"
    },
    "/python-patterns/strategy-pattern": {
      "title": "Strategy Pattern · Python Patterns",
      "description": "Python pattern guide: Pluggable algorithms. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/strategy-pattern"
    },
    "/python-patterns/error-handling": {
      "title": "Error Handling · Python Patterns",
      "description": "Python pattern guide: Exceptions and results. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/error-handling"
    },
    "/python-patterns/logging-patterns": {
      "title": "Logging · Python Patterns",
      "description": "Python pattern guide: Structured observability. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/logging-patterns"
    },
    "/python-patterns/configuration": {
      "title": "Configuration · Python Patterns",
      "description": "Python pattern guide: pydantic-settings. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/configuration"
    },
    "/python-patterns/cli-design": {
      "title": "CLI Design · Python Patterns",
      "description": "Python pattern guide: Typer and Click. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/cli-design"
    },
    "/python-patterns/async-patterns": {
      "title": "Async Patterns · Python Patterns",
      "description": "Python pattern guide: asyncio best practices. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/async-patterns"
    },
    "/python-patterns/clean-architecture": {
      "title": "Clean Architecture · Python Patterns",
      "description": "Python pattern guide: Layered design. Examples and tradeoffs on PythonTeacher.",
      "ogImageId": "python-patterns/clean-architecture"
    }
  }
} as const;
